import { NgModule } from '@angular/core';
import {
	MatAutocompleteModule, MatCheckboxModule, MatDatepickerModule, MatFormFieldModule,
	MatInputModule, MatRadioModule, MatSelectModule, MatSliderModule,
	MatSlideToggleModule,
	MatMenuModule, MatSidenavModule, MatToolbarModule,
	MatCardModule, MatDividerModule, MatExpansionModule, MatGridListModule,
	MatListModule, MatStepperModule, MatTabsModule, MatTreeModule,
	MatButtonModule, MatButtonToggleModule, MatBadgeModule, MatChipsModule,
	MatIconModule, MatProgressSpinnerModule, MatProgressBarModule,
	MatBottomSheetModule, MatDialogModule, MatSnackBarModule, MatTooltipModule,
	MatPaginatorModule, MatSortModule, MatTableModule, MatNativeDateModule,
} from '@angular/material';
@NgModule({

	imports: [
		// Form Controls
		MatAutocompleteModule,
		MatCheckboxModule,
		MatDatepickerModule,
		MatFormFieldModule,
		MatInputModule,
		MatRadioModule,
		MatSelectModule,
		MatSliderModule,
		MatSlideToggleModule,
		// Navigation
		MatMenuModule,
		MatSidenavModule,
		MatToolbarModule,
		// Layout
		MatCardModule,
		MatDividerModule,
		MatExpansionModule,
		MatGridListModule,
		MatListModule,
		MatStepperModule,
		MatTabsModule,
		MatTreeModule,
		// Buttons & Indicators
		MatButtonModule,
		MatButtonToggleModule,
		MatBadgeModule,
		MatChipsModule,
		MatIconModule,
		MatProgressSpinnerModule,
		MatProgressBarModule,
		// Popups & Modals
		MatBottomSheetModule,
		MatDialogModule,
		MatSnackBarModule,
		MatTooltipModule,
		// Data table
		MatPaginatorModule,
		MatSortModule,
		MatTableModule,
	],
	exports: [
		MatAutocompleteModule,
		MatCheckboxModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatFormFieldModule,
		MatInputModule,
		MatRadioModule,
		MatSelectModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatMenuModule,
		MatSidenavModule,
		MatToolbarModule,
		MatCardModule,
		MatDividerModule,
		MatExpansionModule,
		MatGridListModule,
		MatListModule,
		MatStepperModule,
		MatTabsModule,
		MatTreeModule,
		MatButtonModule,
		MatButtonToggleModule,
		MatBadgeModule,
		MatChipsModule,
		MatIconModule,
		MatProgressSpinnerModule,
		MatProgressBarModule,
		MatBottomSheetModule,
		MatDialogModule,
		MatSnackBarModule,
		MatTooltipModule,
		MatPaginatorModule,
		MatSortModule,
		MatTableModule,
	]
})
export class MaterialModule { }
